#if !canImport(ObjectiveC)
import XCTest

extension JSONTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__JSONTests = [
        ("testAccess", testAccess),
        ("testAccessInvalidArray", testAccessInvalidArray),
        ("testAccessInvalidDictionary", testAccessInvalidDictionary),
        ("testAccessInvalidJson", testAccessInvalidJson),
        ("testAccessInvalidRoot", testAccessInvalidRoot),
        ("testAccessKeyNotFoundArray", testAccessKeyNotFoundArray),
        ("testAccessKeyNotFoundDictionary", testAccessKeyNotFoundDictionary),
    ]
}

extension SerializationTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SerializationTests = [
        ("testCanSerializeEntity", testCanSerializeEntity),
        ("testCanSerializeEntityChecksComponents", testCanSerializeEntityChecksComponents),
        ("testCanSerializeEntityFailsOnNonSerializableComponent", testCanSerializeEntityFailsOnNonSerializableComponent),
        ("testCanSerializeSpace", testCanSerializeSpace),
        ("testCanSerializeSpaceChecksComponents", testCanSerializeSpaceChecksComponents),
        ("testCanSerializeSpaceFailsOnNonSerializableComponent", testCanSerializeSpaceFailsOnNonSerializableComponent),
        ("testCanSerializeSpaceFailsOnNonSerializableSubspace", testCanSerializeSpaceFailsOnNonSerializableSubspace),
        ("testDeserializePreset", testDeserializePreset),
        ("testFullDeserialize", testFullDeserialize),
        ("testPresetCannotRepresentPresets", testPresetCannotRepresentPresets),
        ("testPresetDefaultVariableTypeError", testPresetDefaultVariableTypeError),
        ("testPresetExpansion", testPresetExpansion),
        ("testPresetMissingVariableError", testPresetMissingVariableError),
        ("testPresetSerialization", testPresetSerialization),
        ("testPresetSerializedDataDifferentTypeError", testPresetSerializedDataDifferentTypeError),
        ("testPresetSerializedDataNotDictionaryError", testPresetSerializedDataNotDictionaryError),
        ("testPresetVariableTypeError", testPresetVariableTypeError),
        ("testRecursivePresetExpansion", testRecursivePresetExpansion),
        ("testReplacePresetVariables", testReplacePresetVariables),
        ("testSerializationCodableType", testSerializationCodableType),
        ("testSerializationType", testSerializationType),
        ("testSerializeEntity", testSerializeEntity),
        ("testSerializeEntityError", testSerializeEntityError),
        ("testSerializeSpace", testSerializeSpace),
        ("testSerializeSpaceEntityError", testSerializeSpaceEntityError),
        ("testSerializeSpaceSubspaceError", testSerializeSpaceSubspaceError),
        ("testSimplePresetDeserialization", testSimplePresetDeserialization),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(JSONTests.__allTests__JSONTests),
        testCase(SerializationTests.__allTests__SerializationTests),
    ]
}
#endif
