#if !canImport(ObjectiveC)
import XCTest

extension SerializationTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SerializationTests = [
        ("testDeserializePreset", testDeserializePreset),
        ("testFullDeserialize", testFullDeserialize),
        ("testPresetCannotRepresentPresets", testPresetCannotRepresentPresets),
        ("testPresetDefaultVariableTypeError", testPresetDefaultVariableTypeError),
        ("testPresetExpansion", testPresetExpansion),
        ("testPresetSerializedDataDifferentTypeError", testPresetSerializedDataDifferentTypeError),
        ("testPresetSerializedDataNotDictionaryError", testPresetSerializedDataNotDictionaryError),
        ("testPresetVariableTypeError", testPresetVariableTypeError),
        ("testRecursivePresetExpansion", testRecursivePresetExpansion),
        ("testReplacePresetVariables", testReplacePresetVariables),
        ("testSerializationType", testSerializationType),
        ("testSerializeEntity", testSerializeEntity),
        ("testSerializeEntityError", testSerializeEntityError),
        ("testSerializeSpace", testSerializeSpace),
        ("testSerializeSpaceEntityError", testSerializeSpaceEntityError),
        ("testSerializeSpaceSubspaceError", testSerializeSpaceSubspaceError),
        ("testSimplePresetDeserialization", testSimplePresetDeserialization),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(SerializationTests.__allTests__SerializationTests),
    ]
}
#endif
